steps:
  - name: 'Unit Test :boom:'
    command: bundle exec rake test
    agents:
      queue: $QUEUE_NAME
    plugins:
      ecr#v1.2.0:
        login: true
      docker-compose#v3.0.3:
        run: bash
