steps:
  - name: 'Unit Test :boom:'
    command: bundle exec rake test
    agents:
      queue: 'testscripts42'
    plugins:
      - ecr#v1.2.0:
          login: true
      - docker-compose#v3.0.0:
        run: bash
