#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.15
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative 'lexer'

module Unit
  class Parser < Racc::Parser

module_eval(<<'...end parser_definition.y/module_eval...', 'parser_definition.y', 72)
  def parse(input)
    #Takes the results from the lexer's tokenize method and returns stuff
    @tokens = input
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end parser_definition.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    32,    33,    34,    35,    36,    37,    39,    38,    31,    40,
    46,    49,    43,    45,    48,    52,    52,    54,    56,    52,
    24,    51,    33,    34,    41,    29,    28,    30,    27,    26,
    57,    58,    25,    34,    33,    59,    60,    61 ]

racc_action_check = [
    24,    24,    24,    24,    24,    24,    24,    24,    24,    24,
    26,    27,    26,    26,    27,    29,    30,    29,    30,    28,
     0,    28,    46,    46,    25,    19,    18,    21,    16,    15,
    31,    40,     1,    49,    52,    57,    59,    60 ]

racc_action_pointer = [
    18,    32,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    18,    17,   nil,    15,    14,
   nil,    16,   nil,   nil,    -3,    24,     8,     9,    17,    13,
    14,    28,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,   nil,    18,   nil,   nil,    28,
   nil,   nil,    30,   nil,   nil,   nil,   nil,    32,   nil,    25,
    33,   nil ]

racc_action_default = [
   -45,   -45,    -1,    -2,    -3,    -4,    -5,    -6,    -7,    -8,
    -9,   -10,   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -18,
   -19,   -20,   -21,   -22,   -45,   -45,   -45,   -45,   -45,   -45,
   -45,   -45,   -36,   -37,   -38,   -39,   -40,   -41,   -42,   -43,
   -45,    62,   -23,   -24,   -32,   -33,   -45,   -34,   -35,   -45,
   -26,   -27,   -45,   -30,   -31,   -28,   -29,   -45,   -44,   -45,
   -45,   -25 ]

racc_goto_table = [
    16,    12,     4,     5,     6,    17,     7,     8,     9,    10,
    11,     3,    13,    14,    15,     1,     2,    18,    19,    20,
    21,    22,    23,   nil,   nil,   nil,    42,   nil,    50,    53,
    55,    44,    47 ]

racc_goto_check = [
    16,    12,     4,     5,     6,    17,     7,     8,     9,    10,
    11,     3,    13,    14,    15,     1,     2,    18,    19,    20,
    21,    22,    23,   nil,   nil,   nil,    16,   nil,    16,    16,
    16,    17,    17 ]

racc_goto_pointer = [
   nil,    15,    16,    11,     2,     3,     4,     6,     7,     8,
     9,    10,     1,    12,    13,    14,     0,     5,    17,    18,
    19,    20,    21,    22 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  3, 15, :_reduce_23,
  3, 16, :_reduce_24,
  6, 27, :_reduce_25,
  3, 17, :_reduce_26,
  3, 18, :_reduce_27,
  3, 25, :_reduce_28,
  3, 26, :_reduce_29,
  3, 19, :_reduce_30,
  3, 20, :_reduce_31,
  3, 21, :_reduce_32,
  3, 22, :_reduce_33,
  3, 23, :_reduce_34,
  3, 24, :_reduce_35,
  2, 28, :_reduce_36,
  2, 29, :_reduce_37,
  2, 30, :_reduce_38,
  2, 33, :_reduce_39,
  2, 31, :_reduce_40,
  2, 32, :_reduce_41,
  2, 35, :_reduce_42,
  2, 34, :_reduce_43,
  3, 36, :_reduce_44 ]

racc_reduce_n = 45

racc_shift_n = 62

racc_token_table = {
  false => 0,
  :error => 1,
  :SCALAR => 2,
  :MASS_UOM => 3,
  :VOLUME_UOM => 4,
  :TIME_UOM => 5,
  :PATCH_UOM => 6,
  :UNIT_UOM => 7,
  :UNITLESS_UOM => 8,
  :EQUIVALENCE_UOM => 9,
  :PERCENT => 10,
  :SLASH => 11,
  :COLON => 12 }

racc_nt_base = 13

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SCALAR",
  "MASS_UOM",
  "VOLUME_UOM",
  "TIME_UOM",
  "PATCH_UOM",
  "UNIT_UOM",
  "UNITLESS_UOM",
  "EQUIVALENCE_UOM",
  "PERCENT",
  "SLASH",
  "COLON",
  "$start",
  "valid_unit",
  "concentration",
  "concentration_no_denom_scalar",
  "unit_concentration",
  "unit_concentration_no_denom_scalar",
  "unit_less_concentration",
  "unit_less_concentration_no_denom_scalar",
  "rate",
  "rate_no_denom_scalar",
  "volume_rate",
  "volume_rate_no_denom_scalar",
  "equivalence_concentration",
  "equivalence_concentration_no_denom_scalar",
  "rational_concentration",
  "mass",
  "volume",
  "time",
  "unit",
  "unitless",
  "patch",
  "equivalence",
  "percent",
  "solution" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

module_eval(<<'.,.,', 'parser_definition.y', 27)
  def _reduce_23(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 28)
  def _reduce_24(val, _values, result)
     return Concentration.new(val[0], Volume.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 29)
  def _reduce_25(val, _values, result)
     return Concentration.new(Mass.new(val[0], val[3]), Volume.new(val[2], val[5])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 31)
  def _reduce_26(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 32)
  def _reduce_27(val, _values, result)
     return Concentration.new(val[0], Volume.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 34)
  def _reduce_28(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 35)
  def _reduce_29(val, _values, result)
     return Concentration.new(val[0], Volume.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 37)
  def _reduce_30(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 38)
  def _reduce_31(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 40)
  def _reduce_32(val, _values, result)
     return Rate.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 41)
  def _reduce_33(val, _values, result)
     return Rate.new(val[0], Time.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 43)
  def _reduce_34(val, _values, result)
     return Rate.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 44)
  def _reduce_35(val, _values, result)
     return Rate.new(val[0], Time.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 46)
  def _reduce_36(val, _values, result)
     return Mass.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 48)
  def _reduce_37(val, _values, result)
     return Volume.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 50)
  def _reduce_38(val, _values, result)
     return Time.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 52)
  def _reduce_39(val, _values, result)
     return Unit.new(val[0], 'patch') 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 54)
  def _reduce_40(val, _values, result)
     return Unit.new(val[0], 'unit') 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 56)
  def _reduce_41(val, _values, result)
     return Unit.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 58)
  def _reduce_42(val, _values, result)
     return Concentration.new(Mass.new(val[0] * 10, 'mg'), Volume.new(1, 'ml')) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 60)
  def _reduce_43(val, _values, result)
     return Equivalence.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 62)
  def _reduce_44(val, _values, result)
     return Concentration.new(Mass.new(val[0] * 1000, 'mg'), Volume.new(val[2], 'ml')) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Unit
